# Generated by Django 5.2.6 on 2025-09-30 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("title", models.CharField(blank=True, max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="category/photo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="res_categor_name_399363_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Dishes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_dish", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("ingredients", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "image_dish",
                    models.ImageField(blank=True, null=True, upload_to="dishes/photo"),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="res.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блюдо",
                "verbose_name_plural": "Блюда",
                "ordering": ["name_dish"],
                "indexes": [
                    models.Index(
                        fields=["name_dish"], name="res_dishes_name_di_db574e_idx"
                    )
                ],
            },
        ),
    ]
