# Generated by Django 5.2.6 on 2025-10-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(unique=True, verbose_name="Номер стола"),
                ),
                ("seats", models.IntegerField(verbose_name="Количество мест")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя гостя"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Email гостя"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                (
                    "reservation_date",
                    models.DateField(verbose_name="Дата бронирования"),
                ),
                (
                    "reservation_time",
                    models.TimeField(verbose_name="Время бронирования"),
                ),
                ("guests_count", models.IntegerField(verbose_name="Количество гостей")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Дополнительные пожелания"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.table",
                        verbose_name="Стол",
                    ),
                ),
            ],
        ),
    ]
